data_dir = "/var/lib/kapacitor"

[http]
log-enabled = false

[replay]
dir = "/var/lib/kapacitor/replay"

[storage]
boltdb = "/var/lib/kapacitor/kapacitor.db"

[[influxdb]]
urls = ["http://influxdb:8086"]
