data_dir = "/var/lib/kapacitor"

[http]
log-enabled = false
#auth-enabled = true

[replay]
dir = "/var/lib/kapacitor/replay"

[storage]
boltdb = "/var/lib/kapacitor/kapacitor.db"

[[influxdb]]
urls = ["http://influxdb:8086"]
#username = "test"
#password = "secret"
